### ISSUE TITLE
ssl issue?

### ISSUE THREAD

**Issue by siemvaessen** [codeforIATI/codeforiati.github.io#48] opened 2021-01-06 14:56 UTC
Getting invalid cert when looking at codeforiati main page codeforiati.org
<img width="327" alt="Screenshot 2021-01-06 at 15 55 54" src="https://user-images.githubusercontent.com/961036/103782459-c85ea000-5037-11eb-9395-28ab1a9f803c.png">

**Comment by markbrough** [comment] 2021-01-06 15:32
Please can you give us more details of the certificate warning? It works fine for me on Chrome and Firefox on OSX

**Comment by andylolz** [comment] 2021-01-06 15:34
Same… I’m unable to reproduce this…
![Screenshot 2021-01-06 at 15 34 01](https://user-images.githubusercontent.com/464193/103786701-a1eb3580-5034-11eb-9cea-3aa691482c00.png)

**Comment by siemvaessen** [comment] 2021-01-06 16:15
<img width="824" alt="Screenshot 2021-01-06 at 17 13 36" src="https://user-images.githubusercontent.com/961036/103791439-bdf5d380-5042-11eb-963d-632204c44092.png">

**Comment by andylolz** [comment] 2021-01-06 16:17
This looks like chrome to me… Any more details you can provide here, @siemvaessen?

**Comment by andylolz** [comment] 2021-01-06 16:20
Oh, I see the problem now. I think:
https://www.codeforiati.org

…errors, but:
https://codeforiati.org

…works.

**Comment by andylolz** [comment] 2021-01-06 16:37
Bear with me – I’ll have a go at a fix now!

**Comment by andylolz** [comment] 2021-01-06 16:38
@siemvaessen would you mind giving it another go to see if that has fixed it for you?

**Comment by andylolz** [comment] 2021-01-19 10:07
Closing because I’m pretty sure this is fixed now.

**Closed as completed by andylolz** 2021-01-19 10:07 UTC
